#!/bin/sh

# Get the test coverage
coverage=$(npm run test:cov)

echo "Coverage is $coverage%"

# Check if the test coverage is less than 98%
if [ "$coverage" -lt 98 ]; then
  echo "Test coverage is less than 98%. Please fix the tests before committing."
  exit 1
fi