#!/bin/sh

# Run the tests with coverage and capture the output
coverage=$(npm run test:cov | grep -oP '(?<=Coverage is ).*(?=%)')

# Check if coverage value is empty
if [ -z "$coverage" ]; then
  echo "Failed to retrieve coverage percentage. Please check your test script."
  exit 1
fi

echo "Coverage is $coverage%"

# Check if the test coverage is less than 98%
if [ "$coverage" -lt 98 ]; then
  echo "Test coverage is less than 98%. Please fix the tests before committing."
  exit 1
fi